### ISSUE TITLE
Have to cd to /home/karma in .drone.yml

### ISSUE THREAD

**Issue by bsimpson53** [newcrossfoodcoop/nxfc_karma#1]
On the nxfc code base I'm finding that I have to `cd /home/karma` in the `.drone.yml`so that it doesn't pick up the repo gulpfile instead of the container gulpfile

```
  karma:
    image: newcrossfoodcoop/nxfc_karma:v0.1.0
    commands:
      - cd /home/karma
      - gulp karma --conf /drone/src/karma.conf.js
```
